import {Project} from "@/components/myProjects/type";

export const projects: Project[] = [
    {
        kind: "plant",
        name: "Jiatong",
        site: "Rudong · China",
        product: "POY & FDY coils",
        capacity: {value: "90,000", unit: "coils / day"},
        flowLabel: "Material flow — designed",
        flow: ["Winders", "Conveying", "Palletizing"],
        status: "COMMISSIONED",
    },
    {
        kind: "plant",
        name: "Sisecam",
        site: "Balıkesir · Turkey",
        product: "Fiberglass coils",
        capacity: {value: "8,000", unit: "coils / day"},
        flowLabel: "Material flow — designed",
        flow: ["Winders", "Conveying", "Pre-pallet process"],
        status: "COMMISSIONED",
    },
    {
        kind: "plant",
        name: "Shanli",
        site: "Fuzhou · China",
        product: "POY & FDY coils",
        capacity: {value: "65,000", unit: "coils / day"},
        flowLabel: "Material flow — designed",
        flow: ["Winders", "Conveying", "Palletizing"],
        status: "COMMISSIONED",
    },
    {
        kind: "plant",
        name: "Brilen",
        site: "Zaragoza · Spain",
        product: "HTY coils",
        highlight: "Winder-to-operator handling",
        flowLabel: "Material flow — designed",
        flow: ["Winders", "Conveying", "Operator trolleys"],
        status: "COMMISSIONED",
    },
    {
        kind: "plant",
        name: "Shaw",
        site: "Andalusia · Alabama, USA",
        product: "BCF coils",
        highlight: "AGV automatic warehouse",
        flowLabel: "Material flow — designed",
        flow: ["Winders", "Conveying", "AGV warehouse"],
        status: "COMMISSIONED",
    },
    {
        kind: "plant",
        name: "Baker Hughes",
        site: "Houston · Texas, USA",
        product: "Gas turbine test bench · R&D",
        highlight: "Commissioning & turbine control",
        flowLabel: "Scope",
        flow: ["Commissioning", "Turbine test", "Control & monitoring"],
        status: "CURRENT",
    },
    {
        kind: "web",
        name: "Emplhub CRM",
        type: "FULL-STACK",
        description:
            "Business management app for employees and per-client activities. Clients log in too, to follow their activity progress.",
        stack: ["React", "Node.js", "Express", "MongoDB"],
        flowLabel: "Architecture",
        flow: ["Client portal", "REST API", "Database"],
    },
    {
        kind: "web",
        name: "TeamsChatExporter",
        type: "TOOL",
        description:
            "Exports the Teams chats you choose into clean, self-contained HTML files for archiving and sharing.",
        stack: ["TypeScript", "Node.js", "Graph API"],
        flowLabel: "Pipeline",
        flow: ["Teams export", "Parser", "HTML"],
    },
    {
        kind: "web",
        name: "PLC ↔ Arduino display",
        type: "EMBEDDED",
        description:
            "Bridges a Siemens PLC to Arduino over Ethernet to drive several 7-segment displays in real time.",
        stack: ["Arduino", "C++", "Ethernet", "S7"],
        flowLabel: "Signal path",
        flow: ["PLC", "Ethernet", "Arduino", "7-seg displays"],
    },
    {
        kind: "web",
        name: "This portfolio",
        type: "PORTFOLIO",
        description:
            "The site you’re looking at — an Ubuntu-themed portfolio with a 3D globe, HMI panel and terminal.",
        stack: ["Next.js", "TypeScript", "Tailwind", "Three.js"],
        flowLabel: "Pipeline",
        flow: ["Next.js", "Build", "Deploy"],
    },
];
