import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import localFont from "next/font/local";

const poppins = localFont({
    src: [
        {
            path: "../../public/fonts/poppins/Poppins-Light.ttf",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../public/fonts/poppins/Poppins-Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/poppins/Poppins-Medium.ttf",
            weight: "500",
            style: "normal",
        },
        {
            path: "../../public/fonts/poppins/Poppins-SemiBold.ttf",
            weight: "600",
            style: "normal",
        },
        {
            path: "../../public/fonts/poppins/Poppins-Bold.ttf",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-poppins",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html
            lang="en"
            className={`dark ubuntu ${poppins.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <Navbar/>
        <main className="flex-1">{children}</main>
        </body>
        </html>
    );
}
